// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOUfUR1FyK54go3Zb_zd6fc4rQCcdMN2A',
    appId: '1:3586048145:web:dc00488deeeb77c1fc3f30',
    messagingSenderId: '3586048145',
    projectId: 'ppl-simogura',
    authDomain: 'ppl-simogura.firebaseapp.com',
    storageBucket: 'ppl-simogura.firebasestorage.app',
    measurementId: 'G-2F4H9P2C0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXFB-FVWA_THTH5hIxFvS9BmF5lRdjH0U',
    appId: '1:3586048145:android:f330af196c6aa067fc3f30',
    messagingSenderId: '3586048145',
    projectId: 'ppl-simogura',
    storageBucket: 'ppl-simogura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhOi_0oDVDOEJgILlkL9ytLxBJZiJ9Nk0',
    appId: '1:3586048145:ios:17165222bf436d7afc3f30',
    messagingSenderId: '3586048145',
    projectId: 'ppl-simogura',
    storageBucket: 'ppl-simogura.firebasestorage.app',
    iosBundleId: 'com.example.simogura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhOi_0oDVDOEJgILlkL9ytLxBJZiJ9Nk0',
    appId: '1:3586048145:ios:17165222bf436d7afc3f30',
    messagingSenderId: '3586048145',
    projectId: 'ppl-simogura',
    storageBucket: 'ppl-simogura.firebasestorage.app',
    iosBundleId: 'com.example.simogura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOUfUR1FyK54go3Zb_zd6fc4rQCcdMN2A',
    appId: '1:3586048145:web:76f321d8241d6a5ffc3f30',
    messagingSenderId: '3586048145',
    projectId: 'ppl-simogura',
    authDomain: 'ppl-simogura.firebaseapp.com',
    storageBucket: 'ppl-simogura.firebasestorage.app',
    measurementId: 'G-YQKSTE0QR6',
  );
}
