extend type Account {
  """
  ✨ List `Device` objects in a one-to-many relationship (where `Device`.`owner` is this object).
  """
  devices_on_owner(
    """
    Filter condition to narrow down the query results.
    """
    where: Device_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Device_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Device_Having
  ): [Device!]! @fdc_generated(from: "Device.owner", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Account", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Account` table.
  """
  _count: Int! @fdc_generated(from: "Account.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `lastLoginAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  lastLoginAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.lastLoginAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `passwordHash` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  passwordHash_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.passwordHash", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `role` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  role_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.role", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Account` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Account.username", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Account` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Account.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `lastLoginAt` field in the `Account` table.
  """
  lastLoginAt_min: Timestamp @fdc_generated(from: "Account.lastLoginAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Account` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Account.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `lastLoginAt` field in the `Account` table.
  """
  lastLoginAt_max: Timestamp @fdc_generated(from: "Account.lastLoginAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Account.id", purpose: ENTITY_ID)
}
extend type Device {
  """
  ✨ List `KolamReading` objects in a one-to-many relationship (where `KolamReading`.`device` is this object).
  """
  kolamReadings_on_device(
    """
    Filter condition to narrow down the query results.
    """
    where: KolamReading_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [KolamReading_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: KolamReading_Having
  ): [KolamReading!]! @fdc_generated(from: "KolamReading.device", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Device", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Device` table.
  """
  _count: Int! @fdc_generated(from: "Device.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Device` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Device.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Device` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Device.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Device` table where the `deviceId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  deviceId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Device.deviceId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Device` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Device.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Device` table where the `location` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  location_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Device.location", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Device` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Device.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Device` table where the `ownerId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ownerId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Device.ownerId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Device` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Device.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Device` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Device.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Device.id", purpose: ENTITY_ID)
}
extend type KolamReading {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "KolamReading", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `KolamReading` table.
  """
  _count: Int! @fdc_generated(from: "KolamReading.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `KolamReading` table where the `deviceId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  deviceId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "KolamReading.deviceId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `KolamReading` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "KolamReading.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `KolamReading` table where the `ph` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ph_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "KolamReading.ph", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `KolamReading` table where the `temperature` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  temperature_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "KolamReading.temperature", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `KolamReading` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "KolamReading.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `KolamReading` table where the `waterHeight` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  waterHeight_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "KolamReading.waterHeight", purpose: QUERY_COUNT)
  """
  ✨ Sum the `ph` field in the `KolamReading` table.
  """
  ph_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "KolamReading.ph", purpose: QUERY_SUM)
  """
  ✨ Sum the `temperature` field in the `KolamReading` table.
  """
  temperature_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "KolamReading.temperature", purpose: QUERY_SUM)
  """
  ✨ Sum the `waterHeight` field in the `KolamReading` table.
  """
  waterHeight_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "KolamReading.waterHeight", purpose: QUERY_SUM)
  """
  ✨ Average the `ph` field in the `KolamReading` table.
  """
  ph_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "KolamReading.ph", purpose: QUERY_AVG)
  """
  ✨ Average the `temperature` field in the `KolamReading` table.
  """
  temperature_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "KolamReading.temperature", purpose: QUERY_AVG)
  """
  ✨ Average the `waterHeight` field in the `KolamReading` table.
  """
  waterHeight_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "KolamReading.waterHeight", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `ph` field in the `KolamReading` table.
  """
  ph_min: Float @fdc_generated(from: "KolamReading.ph", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `temperature` field in the `KolamReading` table.
  """
  temperature_min: Float @fdc_generated(from: "KolamReading.temperature", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `timestamp` field in the `KolamReading` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "KolamReading.timestamp", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `waterHeight` field in the `KolamReading` table.
  """
  waterHeight_min: Float @fdc_generated(from: "KolamReading.waterHeight", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `ph` field in the `KolamReading` table.
  """
  ph_max: Float @fdc_generated(from: "KolamReading.ph", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `temperature` field in the `KolamReading` table.
  """
  temperature_max: Float @fdc_generated(from: "KolamReading.temperature", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `timestamp` field in the `KolamReading` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "KolamReading.timestamp", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `waterHeight` field in the `KolamReading` table.
  """
  waterHeight_max: Float @fdc_generated(from: "KolamReading.waterHeight", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "KolamReading.id", purpose: ENTITY_ID)
}
