type Account @table {
  id: UUID! @default(expr: "uuidV4()")
  username: String!
  passwordHash: String!
  createdAt: Timestamp! @default(expr: "request.time")
  role: String!
  lastLoginAt: Timestamp
}

type Device @table {
  id: UUID! @default(expr: "uuidV4()")
  ownerId: UUID!
  owner: Account! @ref(fields: ["ownerId"])
  deviceId: String!
  name: String!
  createdAt: Timestamp! @default(expr: "request.time")
  location: String
  description: String
}

type KolamReading @table {
  id: UUID! @default(expr: "uuidV4()")
  deviceId: UUID!
  device: Device! @ref(fields: ["deviceId"])
  timestamp: Timestamp! @default(expr: "request.time")
  ph: Float!
  temperature: Float!
  waterHeight: Float!
}
